apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    chart: adguard-home
    targetRevision: 1.5.1
    helm:
      values: |
        service:
          main:
            type: LoadBalancer # This gives AdGuard its own IP for DNS
        persistence:
          config:
            enabled: true
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
